services:
  aggregator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_PATH=/app/data/events.db
    networks:
      - internal_net
      
  publisher:
    build: .
    command: ["python", "-m", "src.publisher"]
    environment:
      - API_URL=http://aggregator:8080
    networks:
      - internal_net


volumes:
  sqlite_data:

networks:
  internal_net:
    driver: bridge
